# Generated by Django 5.0 on 2026-05-09 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7)),
                ('accent_color', models.CharField(default='#3b82f6', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#111827', max_length=7)),
                ('custom_css', models.TextField(blank=True)),
                ('email_header', models.TextField(blank=True)),
                ('email_footer', models.TextField(blank=True)),
                ('email_from_name', models.CharField(blank=True, max_length=255)),
                ('email_from_address', models.EmailField(blank=True, max_length=254)),
                ('features', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_white_labels', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='white_label', to='accounts.organization')),
            ],
            options={
                'db_table': 'white_labels',
            },
        ),
        migrations.CreateModel(
            name='WhiteLabelDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('white_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='white_label.whitelabel')),
            ],
            options={
                'db_table': 'white_label_domains',
            },
        ),
    ]
