# Generated by Django 5.0 on 2026-05-20 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0004_campaign_bid_floor_campaign_rtb_timeout_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('twilio_call_sid', models.CharField(max_length=100)),
                ('twilio_queue_sid', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('connected', 'Connected'), ('abandoned', 'Abandoned'), ('timeout', 'Timeout')], default='waiting', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('wait_seconds', models.IntegerField(default=0)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queue_entries', to='accounts.organization')),
            ],
            options={
                'db_table': 'call_queue',
                'ordering': ['enqueued_at'],
            },
        ),
    ]
