# Generated by Django 5.0 on 2026-05-06 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCallBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('is_active', models.BooleanField(default=False, help_text='When True, calls with no caller ID are rejected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_call_block', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Anonymous Call Block',
                'verbose_name_plural': 'Anonymous Call Blocks',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('fraud', 'Fraud'), ('manual', 'Manually Added'), ('auto_detected', 'Auto Detected')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = permanent block', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, help_text='Leave blank to block org-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_numbers', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Blacklist Entry',
                'verbose_name_plural': 'Blacklist Entries',
                'indexes': [models.Index(fields=['organization_id', 'phone_number', 'is_active'], name='spam_protec_organiz_b27d04_idx'), models.Index(fields=['organization_id', 'campaign', 'phone_number', 'is_active'], name='spam_protec_organiz_ef5068_idx')],
                'unique_together': {('organization_id', 'campaign', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='SpamReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('block_reason', models.CharField(choices=[('blacklisted', 'Blacklisted Number'), ('anonymous', 'Anonymous Call'), ('duplicate', 'Duplicate Call')], max_length=20)),
                ('twilio_call_sid', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spam_reports', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Spam Report',
                'verbose_name_plural': 'Spam Reports',
                'indexes': [models.Index(fields=['organization_id', 'created_at'], name='spam_protec_organiz_2785b9_idx'), models.Index(fields=['phone_number', 'organization_id'], name='spam_protec_phone_n_814b88_idx')],
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelist_entries', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, help_text='Leave blank to whitelist org-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_numbers', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Whitelist Entry',
                'verbose_name_plural': 'Whitelist Entries',
                'indexes': [models.Index(fields=['organization_id', 'phone_number', 'is_active'], name='spam_protec_organiz_124d09_idx')],
                'unique_together': {('organization_id', 'campaign', 'phone_number')},
            },
        ),
    ]
