# Generated by Django 5.0 on 2026-05-20 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0004_campaign_bid_floor_campaign_rtb_timeout_seconds'),
        ('routing', '0001_initial'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionPixel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, help_text='Unique token used in postback URL', max_length=64, unique=True)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_pixels', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_pixels', to='accounts.organization')),
            ],
            options={
                'db_table': 'conversion_pixels',
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_number', models.CharField(blank=True, max_length=20)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('raw_payload', models.JSONField(default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='routing.calllog')),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webhooks.conversionpixel')),
            ],
            options={
                'db_table': 'conversion_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
