# Generated by Django 5.0 on 2026-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code (USD, EUR, GBP, etc)', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
