# Generated by Django 5.0 on 2026-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingaccount_currency_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='capitalist_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='capitalist_payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coingate_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coingate_payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, default='stripe', max_length=20),
        ),
    ]
