# Generated by Django 5.0 on 2026-05-05 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('publishers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=255)),
                ('number_type', models.CharField(choices=[('local', 'Local'), ('toll_free', 'Toll Free'), ('mobile', 'Mobile')], default='local', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('pending', 'Pending')], default='active', max_length=20)),
                ('twilio_sid', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(default='US', max_length=5)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_numbers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.organization')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to='publishers.publisher')),
            ],
            options={
                'db_table': 'phone_numbers',
                'ordering': ['-created_at'],
            },
        ),
    ]
