# Generated by Django 5.0 on 2026-05-09 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twilio_call_sid', models.CharField(blank=True, db_index=True, max_length=50)),
                ('caller_number', models.CharField(blank=True, max_length=20)),
                ('caller_state', models.CharField(blank=True, max_length=10)),
                ('called_number', models.CharField(blank=True, max_length=20)),
                ('campaign_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('buyer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('publisher_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('voicemail', 'Voicemail'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('routing_type', models.CharField(blank=True, choices=[('rtb', 'RTB'), ('priority', 'Priority'), ('weighted', 'Weighted'), ('round_robin', 'Round Robin')], max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('billable_seconds', models.IntegerField(default=0)),
                ('is_converted', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('payout', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('winning_bid', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('auction_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='accounts.organization')),
            ],
            options={
                'db_table': 'call_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='call_record_organiz_6b65cd_idx'), models.Index(fields=['organization', 'campaign_id', 'created_at'], name='call_record_organiz_c3a52f_idx'), models.Index(fields=['organization', 'buyer_id', 'created_at'], name='call_record_organiz_e31e80_idx'), models.Index(fields=['organization', 'publisher_id', 'created_at'], name='call_record_organiz_131cd2_idx'), models.Index(fields=['status', 'created_at'], name='call_record_status_4febef_idx')],
            },
        ),
    ]
