# Generated by Django 5.0 on 2026-05-04 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('routing_type', models.CharField(choices=[('external', 'External Number'), ('sip', 'SIP Endpoint')], default='external', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('sip_endpoint', models.CharField(blank=True, max_length=255)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_call_duration', models.IntegerField(default=0)),
                ('max_concurrency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buyers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='accounts.organization')),
            ],
            options={
                'db_table': 'buyers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerCap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_calls_daily', models.IntegerField(default=0)),
                ('max_calls_monthly', models.IntegerField(default=0)),
                ('max_calls_global', models.IntegerField(default=0)),
                ('max_concurrency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cap', to='buyers.buyer')),
            ],
            options={
                'db_table': 'buyer_caps',
            },
        ),
        migrations.CreateModel(
            name='BuyerCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='buyers.buyer')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_assignments', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'buyer_campaigns',
                'ordering': ['priority'],
                'unique_together': {('buyer', 'campaign')},
            },
        ),
    ]
