# Generated by Django 5.0 on 2026-05-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='rtb_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='buyercampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_buyers', to='campaigns.campaign'),
        ),
    ]
