# Generated by Django 5.0 on 2026-05-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyer_rtb_endpoint_alter_buyercampaign_campaign'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyercampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='campaigns.campaign'),
        ),
    ]
