# Generated by Django 5.0 on 2026-05-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_alter_buyercampaign_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyercampaign',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_buyers', to='buyers.buyer'),
        ),
    ]
