# Generated by Django 5.0 on 2026-05-20 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_alter_buyercampaign_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='dup_window_days',
            field=models.IntegerField(default=30, help_text='Days to block same caller from reaching this buyer again'),
        ),
        migrations.CreateModel(
            name='BuyerSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buyers.buyer')),
            ],
            options={
                'db_table': 'buyer_schedules',
                'unique_together': {('buyer', 'day_of_week')},
            },
        ),
    ]
