# Generated by Django 5.0 on 2026-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_buyer_dup_window_days_buyerschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='quality_score',
            field=models.IntegerField(default=50, help_text='0-100 quality score based on call outcomes'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='quality_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
