# Generated by Django 5.0 on 2026-05-09 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0002_buyer_rtb_endpoint_alter_buyercampaign_campaign'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTBAuction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('caller_state', models.CharField(blank=True, default='', max_length=10)),
                ('twilio_call_sid', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('timeout', 'Timeout'), ('no_bids', 'No Bids')], default='open', max_length=20)),
                ('winning_bid', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtb_auctions', to='campaigns.campaign')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'RTB Auction',
                'verbose_name_plural': 'RTB Auctions',
            },
        ),
        migrations.CreateModel(
            name='RTBBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('timeout', 'Timeout'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('response_ms', models.IntegerField(default=0, help_text='How fast the buyer responded in ms')),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rtb.rtbauction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtb_bids', to='buyers.buyer')),
            ],
            options={
                'verbose_name': 'RTB Bid',
                'verbose_name_plural': 'RTB Bids',
            },
        ),
        migrations.AddIndex(
            model_name='rtbauction',
            index=models.Index(fields=['organization_id', 'created_at'], name='rtb_rtbauct_organiz_468ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='rtbauction',
            index=models.Index(fields=['campaign', 'status'], name='rtb_rtbauct_campaig_c87c76_idx'),
        ),
        migrations.AddIndex(
            model_name='rtbbid',
            index=models.Index(fields=['auction', 'status'], name='rtb_rtbbid_auction_696243_idx'),
        ),
        migrations.AddIndex(
            model_name='rtbbid',
            index=models.Index(fields=['buyer', 'status'], name='rtb_rtbbid_buyer_i_379fc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rtbbid',
            unique_together={('auction', 'buyer')},
        ),
    ]
