# Generated by Django 5.0 on 2026-05-09 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IVRFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('welcome_message', models.TextField(blank=True)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('voice', models.CharField(default='alice', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivr_flows', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_flows', to='accounts.organization')),
            ],
            options={
                'db_table': 'ivr_flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IVRNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('say', 'Say'), ('gather', 'Gather'), ('dial', 'Dial'), ('hangup', 'Hangup'), ('transfer', 'Transfer'), ('voicemail', 'Voicemail'), ('record', 'Record'), ('pause', 'Pause')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('is_entry_point', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ivr.ivrflow')),
            ],
            options={
                'db_table': 'ivr_nodes',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='IVRNodeTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='ivr.ivrnode')),
                ('to_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='ivr.ivrnode')),
            ],
            options={
                'db_table': 'ivr_node_transitions',
                'unique_together': {('from_node', 'trigger')},
            },
        ),
    ]
