# Generated by Django 5.0 on 2026-05-05 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('buyers', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('publishers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('time_based', 'Time Based'), ('geo_based', 'Geo Based'), ('round_robin', 'Round Robin'), ('weighted', 'Weighted'), ('priority', 'Priority'), ('caller_specific', 'Caller Specific'), ('overflow', 'Overflow'), ('schedule_based', 'Schedule Based'), ('tag_based', 'Tag Based'), ('rtb', 'Real Time Bidding'), ('ping_post', 'Ping Post')], max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='accounts.organization')),
            ],
            options={
                'db_table': 'routing_rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conditions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='routing.routingrule')),
            ],
            options={
                'db_table': 'rule_conditions',
            },
        ),
        migrations.CreateModel(
            name='RuleDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_type', models.CharField(choices=[('phone', 'Phone Number'), ('sip', 'SIP Endpoint'), ('buyer', 'Buyer')], default='phone', max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_destinations', to='buyers.buyer')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='routing.routingrule')),
            ],
            options={
                'db_table': 'rule_destinations',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('destination_number', models.CharField(blank=True, max_length=20)),
                ('twilio_call_sid', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed')], default='ringing', max_length=20)),
                ('caller_area_code', models.CharField(blank=True, max_length=5)),
                ('caller_state', models.CharField(blank=True, max_length=50)),
                ('caller_country', models.CharField(blank=True, max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('twilio_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('buyer_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('publisher_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_sid', models.CharField(blank=True, max_length=100)),
                ('transcription', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='buyers.buyer')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='accounts.organization')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='publishers.publisher')),
                ('routing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='routing.routingrule')),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='call_logs_organiz_4cb942_idx'), models.Index(fields=['campaign', 'created_at'], name='call_logs_campaig_b400d2_idx'), models.Index(fields=['twilio_call_sid'], name='call_logs_twilio__88d49f_idx')],
            },
        ),
    ]
