# Generated by Django 5.0 on 2026-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='sentiment',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcription_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcription_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
