# Generated by Django 5.0 on 2026-05-09 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNIPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('session_duration_minutes', models.IntegerField(default=30)),
                ('fallback_number', models.CharField(blank=True, max_length=20)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dni_pools', to='campaigns.campaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dni_pools', to='accounts.organization')),
            ],
            options={
                'db_table': 'dni_pools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNINumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('disabled', 'Disabled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dni_numbers', to='phone_numbers.phonenumber')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='dni.dnipool')),
            ],
            options={
                'db_table': 'dni_numbers',
            },
        ),
        migrations.CreateModel(
            name='DNISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('gclid', models.CharField(blank=True, max_length=255)),
                ('fbclid', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('landing_page', models.URLField(blank=True)),
                ('assigned_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('called', 'Called'), ('released', 'Released')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dni_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dni.dninumber')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dni.dnipool')),
            ],
            options={
                'db_table': 'dni_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visitor_id', 'status'], name='dni_session_visitor_46825f_idx'), models.Index(fields=['pool', 'status'], name='dni_session_pool_id_c08701_idx'), models.Index(fields=['assigned_number', 'status'], name='dni_session_assigne_ff4e93_idx'), models.Index(fields=['expires_at', 'status'], name='dni_session_expires_884bb2_idx')],
            },
        ),
    ]
