# Generated by Django 5.0 on 2026-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='auto_sms_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='greeting_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='greeting_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recording_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recording_storage',
            field=models.CharField(default='twilio', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='whisper_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='whisper_message',
            field=models.TextField(blank=True),
        ),
    ]
