# Generated by Django 5.0 on 2026-05-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_auto_sms_enabled_campaign_auto_sms_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='queue_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='queue_max_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='queue_max_wait_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='campaign',
            name='queue_message',
            field=models.TextField(blank=True, default='All agents are busy. Please hold.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='queue_music_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
