# Generated by Django 5.0 on 2026-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_queue_enabled_campaign_queue_max_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bid_floor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum acceptable bid amount in RTB auction', max_digits=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rtb_timeout_seconds',
            field=models.IntegerField(default=5, help_text='Seconds buyers have to respond to RTB ping (1-30)'),
        ),
    ]
