# Generated by Django 5.0 on 2026-05-04 04:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unique_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publishers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='accounts.organization')),
            ],
            options={
                'db_table': 'publishers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherCap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_calls_daily', models.IntegerField(default=0)),
                ('max_calls_monthly', models.IntegerField(default=0)),
                ('max_calls_global', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cap', to='publishers.publisher')),
            ],
            options={
                'db_table': 'publisher_caps',
            },
        ),
        migrations.CreateModel(
            name='PublisherCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_assignments', to='campaigns.campaign')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='publishers.publisher')),
            ],
            options={
                'db_table': 'publisher_campaigns',
                'unique_together': {('publisher', 'campaign')},
            },
        ),
    ]
